/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sistema.mercadinho.view;

import com.sistema.mercadinho.dao.ProdutoDAO;
import com.sistema.mercadinho.model.Produto;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rag
 */
public class TelaEstoque extends javax.swing.JFrame {

    ProdutoDAO dao = new ProdutoDAO();

    private static TelaEstoque instancia = null;

    public static void abrir(Component parent) {
        if (instancia == null) {
            instancia = new TelaEstoque();
            instancia.setLocationRelativeTo(parent);
            instancia.setVisible(true);

        } else {
            instancia.setVisible(true); // Garante que não esteja invisível
            instancia.setExtendedState(javax.swing.JFrame.NORMAL); // Desminimiza se estiver minimizada
            instancia.toFront(); // Traz para frente
            instancia.requestFocus(); // Dá o foco
        }
    }

    /**
     * Creates new form TelaEstoque
     */
    public TelaEstoque() {
        initComponents();
        carregarTabela();

        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                instancia = null;
            }
        });

    }

    private void carregarTabela() {
        ArrayList<Produto> listaDeProdutos = dao.listar();

        DefaultTableModel modelo = (DefaultTableModel) tblEstoque.getModel();
        modelo.setRowCount(0);

        for (Produto produto : listaDeProdutos) {
            modelo.addRow(new Object[]{
                produto.getCodigo(),
                produto.getDescricao(),
                produto.getEstoque()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEstoque = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblEstoque = new javax.swing.JTable();
        btnExcluir = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        lblEstoque.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblEstoque.setText("Estoque");

        tblEstoque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código do produto:", "Descrição:", "Quantidade:"
            }
        ));
        jScrollPane3.setViewportView(tblEstoque);

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnCadastrar.setText("Cadastrar novo");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEstoque)
                        .addGap(329, 329, 329)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEstoque)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluir)
                    .addComponent(btnCadastrar))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // 1. Verifica se tem linha selecionada
        int linhaSelecionada = tblEstoque.getSelectedRow();

        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um produto para remover.");
            return;
        }

        // Pega os dados da linha para mostrar na mensagem
        String codigo = tblEstoque.getValueAt(linhaSelecionada, 0).toString();
        String descricao = tblEstoque.getValueAt(linhaSelecionada, 1).toString(); // Pegar o nome ajuda na confirmação

        int opcao = JOptionPane.showConfirmDialog(this,
                "Tem certeza que deseja remover o produto:\n" + descricao + "?",
                "Confirmar Exclusão",
                JOptionPane.YES_NO_OPTION);

        if (opcao == JOptionPane.YES_OPTION) {
            try {
                // Remove do dao
                dao.remover(codigo);

                // Remove da tabela visual
                DefaultTableModel modelo = (DefaultTableModel) tblEstoque.getModel();
                modelo.removeRow(linhaSelecionada);

                JOptionPane.showMessageDialog(this, "Produto removido com sucesso!");

            } catch (Exception e) {
                // Se der erro (ex: produto já foi vendido e tem histórico), cai aqui
                JOptionPane.showMessageDialog(this, "Erro ao remover (Pode haver vendas vinculadas): \n" + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        carregarTabela();
    }//GEN-LAST:event_formWindowActivated

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        TelaCadastroProduto tela = new TelaCadastroProduto(this, true);

        tela.setVisible(true);

        carregarTabela();
    }//GEN-LAST:event_btnCadastrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblEstoque;
    private javax.swing.JTable tblEstoque;
    // End of variables declaration//GEN-END:variables

}
