/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sistema.mercadinho.view;

import com.sistema.mercadinho.dao.FuncionarioDAO;
import com.sistema.mercadinho.model.Funcionario;
import java.awt.Component;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rag
 */
public class TelaListaFuncionarios extends javax.swing.JFrame {

    /**
     * Creates new form TelaListaFuncionarios
     */
    private static TelaListaFuncionarios instancia = null;

    public static void abrir(Component parent) {
        if (instancia == null) {
            instancia = new TelaListaFuncionarios();
            instancia.setLocationRelativeTo(parent);
            instancia.setVisible(true);
        } else {
            instancia.setVisible(true);
            instancia.setExtendedState(javax.swing.JFrame.NORMAL);
            instancia.toFront();
            instancia.requestFocus();
        }
    }
    
    public TelaListaFuncionarios() {
        initComponents();
        preencherTabela();

        // Limpa a instância quando fechar
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                instancia = null;
            }
        });
        
    }
    
    private void preencherTabela() {
        FuncionarioDAO dao = new FuncionarioDAO();
        List<Funcionario> lista = dao.listarTodos(); // Certifique-se que existe o listar() no DAO

        DefaultTableModel modelo = (DefaultTableModel) tblFuncionarios.getModel();
        modelo.setRowCount(0);

        for (Funcionario f : lista) {
            modelo.addRow(new Object[]{
                f.getNome(),
                f.getCPF(),
                f.getCargo()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFuncionarios = new javax.swing.JTable();
        btnCadastrarNovo = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Funcionários Cadastrados");

        tblFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "CPF", "Cargo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblFuncionarios);

        btnCadastrarNovo.setText("Cadastrar novo");
        btnCadastrarNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarNovoActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCadastrarNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(359, 359, 359)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(99, 99, 99)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrarNovo)
                    .addComponent(btnExcluir))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarNovoActionPerformed
        TelaCadastroFuncionario tela = new TelaCadastroFuncionario(this, true);
        tela.setVisible(true); // O código pausa aqui
        
        // Quando fecha, atualiza a tabela
        preencherTabela();
    }//GEN-LAST:event_btnCadastrarNovoActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // 1. Verifica qual linha está selecionada
    int linhaSelecionada = tblFuncionarios.getSelectedRow();
    
    if (linhaSelecionada == -1) {
        JOptionPane.showMessageDialog(this, "Selecione um funcionário para excluir.");
        return;
    }
    
    // 2. Pega o CPF da linha selecionada (assumindo que o CPF é a Coluna 1)
    // getValueAt retorna Object, então convertemos para String
    String cpf = tblFuncionarios.getValueAt(linhaSelecionada, 1).toString();
    
    // 3. Pergunta de segurança (NUNCA exclua direto!)
    int opcao = JOptionPane.showConfirmDialog(this, 
            "Tem certeza que deseja excluir o funcionário do CPF: " + cpf + "?", 
            "Excluir Funcionário", 
            JOptionPane.YES_NO_OPTION);
    
    if (opcao == JOptionPane.YES_OPTION) {
        // 4. Chama o DAO para excluir
        FuncionarioDAO dao = new FuncionarioDAO();
        try {
            dao.remover(cpf); // Você precisa criar esse método no DAO
            
            JOptionPane.showMessageDialog(this, "Excluído com sucesso!");
            
            // 5. Atualiza a tabela para o nome sumir
            preencherTabela();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao excluir: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_btnExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarNovo;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblFuncionarios;
    // End of variables declaration//GEN-END:variables
}
