/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sistema.mercadinho.view;

import com.sistema.mercadinho.dao.ProdutoDAO;
import com.sistema.mercadinho.model.Produto;
import java.awt.Frame;
import javax.swing.JOptionPane;

/**
 *
 * @author rag
 */
public class TelaCadastroProduto extends javax.swing.JDialog {

    private ProdutoDAO dao;

    /**
     * Creates new form CadastroProduto
     */
    public TelaCadastroProduto(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        dao = new ProdutoDAO();

        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtDescricao = new javax.swing.JTextField();
        txtQuantidade = new javax.swing.JTextField();
        txtValorUnit = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Produto");

        jLabel3.setText("Valor Unit.:");

        jLabel4.setText("Quantidade:");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        jLabel1.setText("Código:");

        jLabel2.setText("Descrição:");

        txtDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescricaoActionPerformed(evt);
            }
        });

        txtValorUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorUnitActionPerformed(evt);
            }
        });
        txtValorUnit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValorUnitKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSalvar)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCodigo)
                            .addComponent(txtDescricao)
                            .addComponent(txtValorUnit)
                            .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtValorUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(39, 39, 39)
                .addComponent(btnSalvar)
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // 1. Validação: Verifica se os campos obrigatórios estão vazios
        if (txtCodigo.getText().trim().isEmpty()
                || txtDescricao.getText().trim().isEmpty()
                || txtQuantidade.getText().trim().isEmpty()
                || txtValorUnit.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(this, "Preencha todos os campos!");
            return;
        }

        try {
            // 2. Coleta os dados dos campos de texto
            String codigo = txtCodigo.getText();
            String descricao = txtDescricao.getText();

            // --- CORREÇÃO DO ERRO DO R$ ---
            // Pega o texto, tira R$, tira espaços normais, tira espaços invisíveis e troca vírgula por ponto
            String valorLimpo = txtValorUnit.getText()
                    .replace("R$", "")
                    .replace(" ", "")
                    .replace("\u00A0", "") // Tira espaço invisível que o Java coloca as vezes
                    .replace(",", ".")
                    .trim();

            // Converte para números agora que o texto está limpo
            double valorUnit = Double.parseDouble(valorLimpo);
            int qtdDigitada = Integer.parseInt(txtQuantidade.getText().trim());

            // 3. Lógica Inteligente (HashMap)
            // Busca se o produto já existe na memória
            Produto produtoExistente = dao.consultar(codigo);

            if (produtoExistente == null) {
                // --- CENÁRIO: PRODUTO NOVO ---
                Produto novo = new Produto(codigo, descricao, valorUnit, qtdDigitada);
                dao.cadastrar(novo);
                JOptionPane.showMessageDialog(this, "Produto cadastrado com sucesso!");
            } else {
                // --- CENÁRIO: PRODUTO JÁ EXISTE ---
                int opcao = JOptionPane.showConfirmDialog(this,
                        "O produto '" + produtoExistente.getDescricao() + "' já existe.\n"
                        + "Estoque atual: " + produtoExistente.getEstoque() + "\n"
                        + "Deseja ADICIONAR " + qtdDigitada + " unidades ao estoque?",
                        "Atualizar Estoque",
                        JOptionPane.YES_NO_OPTION);

                if (opcao == JOptionPane.YES_OPTION) {
                    // Soma o estoque antigo com o novo
                    int novoEstoqueTotal = produtoExistente.getEstoque() + qtdDigitada;

                    // Atualiza o objeto na memória (HashMap atualiza automático ao usar set)
                    produtoExistente.setEstoque(novoEstoqueTotal);
                    produtoExistente.setValorUnitario(valorUnit); // Atualiza o preço se tiver mudado
                    produtoExistente.setDescricao(descricao); // Atualiza descrição se tiver mudado

                    JOptionPane.showMessageDialog(this, "Estoque atualizado! Total: " + novoEstoqueTotal);
                } else {
                    return; // Se cancelar, não fecha a janela
                }
            }

            // 4. Fecha a janela de cadastro e volta para o estoque
            dispose();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Erro de número: Verifique se digitou a Quantidade ou Valor corretamente.\nErro técnico: " + e.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro inesperado: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescricaoActionPerformed

    private void txtValorUnitKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorUnitKeyReleased
        String texto = txtValorUnit.getText();
        String apenasNumeros = texto.replaceAll("[^0-9]", "");
        if (!apenasNumeros.isEmpty()) {
            // Transforma em valor real (divide por 100 para ter os centavos)
            double valor = Double.parseDouble(apenasNumeros) / 100;

            // Formata para moeda brasileira
            java.text.NumberFormat nf = java.text.NumberFormat.getCurrencyInstance();
            String textoFormatado = nf.format(valor);

            // Atualiza o campo e joga o cursor para o final
            txtValorUnit.setText(textoFormatado);
        }
    }//GEN-LAST:event_txtValorUnitKeyReleased

    private void txtValorUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorUnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorUnitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JFormattedTextField txtValorUnit;
    // End of variables declaration//GEN-END:variables
}
