/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sistema.mercadinho.view;

import com.sistema.mercadinho.dao.FuncionarioDAO;
import com.sistema.mercadinho.dao.HistoricoVendaDAO;
import com.sistema.mercadinho.dao.ProdutoDAO;
import com.sistema.mercadinho.model.ItemVenda;
import com.sistema.mercadinho.model.Produto;
import com.sistema.mercadinho.model.Venda;
import java.awt.Font;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.formdev.flatlaf.FlatLightLaf;
import com.sistema.mercadinho.dao.ClienteDAO;
import com.sistema.mercadinho.model.Cliente;
import com.sistema.mercadinho.model.Funcionario;
import java.awt.Color;
import javax.swing.JTextField;

/**
 *
 * @author rag
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private Venda vendaAtual;
    private ProdutoDAO estoque;
    private HistoricoVendaDAO historico;
    private FuncionarioDAO cadastroFunc;
    private Produto produtoSelecionado;
    private TelaHistoricoVendas valorComMoeda;
    private Cliente clienteDaVenda = null;

    /**
     * Creates new form TelaVenda
     */
    public TelaPrincipal(ProdutoDAO estoqueOficial) {
        initComponents();
        this.estoque = estoqueOficial;
        vendaAtual = new Venda();
        estoque = new ProdutoDAO();
        cadastroFunc = new FuncionarioDAO();
        txtCodigo.requestFocus();
        estoque.carregarDados();
        historico = new HistoricoVendaDAO();
        historico.carregarDados();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        configurarDesign();

        controlarCaixa(false, null);
        lblNomeCliente.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jDialog3 = new javax.swing.JDialog();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItens = new javax.swing.JTable();
        lblTotal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblEstoque = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCpfCliente = new javax.swing.JFormattedTextField();
        lblNomeCliente = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        btnLoginSistema = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuLogout = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jMenuItem5.setText("jMenuItem5");

        jMenuItem6.setText("jMenuItem6");

        jMenu2.setText("jMenu2");

        jMenuItem7.setText("jMenuItem7");

        jMenuItem8.setText("jMenuItem8");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenuItem10.setText("jMenuItem10");

        jMenuItem12.setText("jMenuItem12");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Código do produto:");

        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoKeyPressed(evt);
            }
        });

        jLabel2.setText("Descrição:");

        txtDescricao.setEditable(false);
        txtDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescricaoActionPerformed(evt);
            }
        });

        tblItens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Preço Unit.", "Qtd.", "Total Item"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblItens.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblItensKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblItens);

        lblTotal.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(0, 153, 51));
        lblTotal.setText("R$ 0,00");

        jLabel3.setText("Preço Unitário:");

        txtValor.setEditable(false);
        txtValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorActionPerformed(evt);
            }
        });

        jLabel4.setText("Quantidade:");

        txtQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidadeActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 51));
        jLabel5.setText("Total:");

        lblEstoque.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        lblEstoque.setForeground(new java.awt.Color(0, 51, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("F2 - Realizar pagamento");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("F1 - Nova venda");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(68, 68, 68)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setText("CPF do cliente:");

        try {
            txtCpfCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpfCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfClienteActionPerformed(evt);
            }
        });

        lblNomeCliente.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNomeCliente.setForeground(new java.awt.Color(0, 204, 0));
        lblNomeCliente.setText("Consumidor FInal");

        btnSair.setBackground(new java.awt.Color(255, 0, 0));
        btnSair.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnSair.setForeground(new java.awt.Color(255, 255, 255));
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnLoginSistema.setBackground(new java.awt.Color(0, 204, 0));
        btnLoginSistema.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnLoginSistema.setForeground(new java.awt.Color(255, 255, 255));
        btnLoginSistema.setText("Entrar");
        btnLoginSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginSistemaActionPerformed(evt);
            }
        });

        jMenuLogout.setText("Menu");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        jMenuItem1.setText("Estoque");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuLogout.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jMenuItem2.setText("Funcionários Cadastrados");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuLogout.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        jMenuItem3.setText("Clientes Cadastrados");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenuLogout.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        jMenuItem4.setText("Histórico de Vendas");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenuLogout.add(jMenuItem4);

        jMenuBar1.add(jMenuLogout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(lblNomeCliente))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 796, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotal)))
                .addGap(252, 252, 252))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLoginSistema)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSair)
                .addGap(126, 126, 126))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnLoginSistema, btnSair});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSair)
                    .addComponent(btnLoginSistema))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomeCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(331, 331, 331)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblTotal))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnLoginSistema, btnSair});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaHistoricoVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaHistoricoVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaHistoricoVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaHistoricoVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TelaPrincipal(new ProdutoDAO()).setVisible(true);
//            }
//        });

        /* Flatlaf */
        try {
            FlatLightLaf.setup();
        } catch (Exception e) {
            System.err.println("Erro ao iniciar FlatLaf");
        }

        java.awt.EventQueue.invokeLater(() -> {
            new TelaPrincipal(new ProdutoDAO()).setVisible(true);
        });
    }

    public void controlarCaixa(boolean ativo, Funcionario funcionario) {
        txtCodigo.setEnabled(ativo);
        txtQuantidade.setEnabled(ativo);
        btnSair.setEnabled(ativo);

        jMenuBar1.setEnabled(ativo);
        btnLoginSistema.setEnabled(!ativo);
        for (int i = 0; i < jMenuBar1.getMenuCount(); i++) {
            jMenuBar1.getMenu(i).setEnabled(ativo);
        }

        if (ativo) {
            this.setTitle("Mercadinho Compre Muito - PDV ABERTO - Operador: " + funcionario.getNome());
            txtDescricao.setText("");
            txtCodigo.requestFocus();
            lblTotal.setText("R$ 0,00");
            lblTotal.setForeground(new Color(0, 153, 51));

            btnLoginSistema.setText("Trocar Operador");
            btnLoginSistema.setBackground(new Color(0, 204, 0));
            btnLoginSistema.setForeground(Color.WHITE);
            btnLoginSistema.setEnabled(true);
            jMenuBar1.setEnabled(ativo);
            txtCodigo.requestFocus();
            txtCpfCliente.setEditable(ativo);
        } else {
            this.setTitle("Mercadinho Compre Muito - PDV FECHADO");
            btnLoginSistema.setFont(new java.awt.Font("Dialog", 1, 18));
            btnLoginSistema.setText("Entrar");
            txtCodigo.setText("");
            txtDescricao.setText("CAIXA FECHADO");
            lblEstoque.setText("");
            txtValor.setText("");
            txtQuantidade.setText("");
            lblTotal.setText("Bloqueado");
            lblTotal.setForeground(java.awt.Color.GRAY);
            txtCpfCliente.setEditable(ativo);
            btnSair.setEnabled(true);

            try {
                DefaultTableModel modelo = (DefaultTableModel) tblItens.getModel();
                modelo.setRowCount(0);
            } catch (Exception e) {
                // Ignora o erro caso a tabela não tenha sido iniciada
            }

            btnLoginSistema.setEnabled(true);
        }
    }

    private void txtDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescricaoActionPerformed
    }//GEN-LAST:event_txtDescricaoActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        String codigo = txtCodigo.getText();
        this.produtoSelecionado = estoque.consultar(codigo);
        if (produtoSelecionado != null) {
            txtDescricao.setText(produtoSelecionado.getDescricao());
            txtValor.setText(String.valueOf(produtoSelecionado.getValorUnitario()));
            lblEstoque.setText("Estoque: " + produtoSelecionado.getEstoque());
            txtQuantidade.requestFocus();

        } else {
            JOptionPane.showMessageDialog(this, "Produto não encontrado.");
            txtDescricao.setText("");
            txtValor.setText("");
            lblEstoque.setText("");
        }
    }//GEN-LAST:event_txtCodigoActionPerformed

    public JTextField getTxtCodigo() {
        return txtCodigo;
    }

    private void txtValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorActionPerformed

    private void txtQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeActionPerformed
        if (produtoSelecionado == null) {
            JOptionPane.showMessageDialog(this, "Por favor, pesquise um produto pelo código primeiro.");
            txtCodigo.requestFocus();
            return;
        }

        try {
            int qtdDesejada = Integer.parseInt(txtQuantidade.getText());

            // Impede quantidade zero ou negativa
            if (qtdDesejada <= 0) {
                JOptionPane.showMessageDialog(this, "A Quantidade deve ser maior que zero.");
                return;
            }

            // Tenta realizar a venda na lógica do objeto
            boolean vendaFoiPossivel = produtoSelecionado.realizarVenda(qtdDesejada);

            if (vendaFoiPossivel) {
                // estoque.atualizar(produtoSelecionado);

                // Adiciona ao carrinho de compras
                ItemVenda item = new ItemVenda(produtoSelecionado, qtdDesejada);
                vendaAtual.adicionarItem(item);

                // Atualiza a Tabela
                DefaultTableModel modelo = (DefaultTableModel) tblItens.getModel();
                String valorComMoeda = String.format("R$ %.2f", item.calcularPrecoItem());
                String PrecoComMoeda = String.format("R$ %.2f", item.getProduto().getValorUnitario());

                modelo.addRow(new Object[]{
                    item.getProduto().getCodigo(),
                    item.getProduto().getDescricao(),
                    PrecoComMoeda,
                    item.getQuantidade(),
                    valorComMoeda
                });

                lblTotal.setText(String.format("R$ %.2f", vendaAtual.getValorTotal()));

                txtCodigo.setText("");
                txtDescricao.setText("");
                txtValor.setText("");
                txtQuantidade.setText("");
                lblEstoque.setText("");

                this.produtoSelecionado = null;

                txtCodigo.requestFocus();

            } else {
                JOptionPane.showMessageDialog(this, "Estoque insuficiente! Restam apenas: " + produtoSelecionado.getEstoque());
                // Seleciona o texto da quantidade para o usuário digitar outro valor
                txtQuantidade.selectAll();
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, digite um número válido (inteiro) na quantidade.");
            txtQuantidade.setText("");
            txtQuantidade.requestFocus();
        }    }//GEN-LAST:event_txtQuantidadeActionPerformed

    private void txtCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_F2) {

            if (vendaAtual.getItemVendaProdutos().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Adicione produtos primeiro!");
                return;
            }

            // Pega o texto do CPF 
            String cpfDigitado = txtCpfCliente.getText();

            ClienteDAO dao = new ClienteDAO();
            Cliente clienteEncontrado = dao.consultar(cpfDigitado);

            if (clienteEncontrado != null) {
                vendaAtual.setCliente(clienteEncontrado);
            } else {
                Cliente c = new Cliente();
                c.setCPF(cpfDigitado);
                c.setNome("Consumidor Final");
                vendaAtual.setCliente(c);
            }

            TelaPagamento pagamento = new TelaPagamento(this, true, vendaAtual);
            pagamento.setLocationRelativeTo(this);
            pagamento.setVisible(true);

            if (pagamento.getPgtConfirmado()) {
                ((DefaultTableModel) tblItens.getModel()).setRowCount(0);
                vendaAtual = new Venda();
            }

        }

        if (evt.getKeyCode() == KeyEvent.VK_F1) {
            lblEstoque.setText("");
            ProdutoDAO dao = new ProdutoDAO();
            for (ItemVenda itemVenda : vendaAtual.getItemVendaProdutos()) {
                Produto produto = itemVenda.getProduto();
            }
            ((DefaultTableModel) tblItens.getModel()).setRowCount(0);
            txtCodigo.setText(null);
            txtDescricao.setText(null);
            txtValor.setText(null);
            txtQuantidade.setText(null);
            vendaAtual = new Venda();
            lblTotal.setText("R$ 0,00");
        }

    }//GEN-LAST:event_txtCodigoKeyPressed

    private void tblItensKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblItensKeyReleased
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_DELETE) {
            int linhaSelecionada = tblItens.getSelectedRow();

            if (linhaSelecionada != -1) {

                int resposta = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir?", "Confirmação", JOptionPane.YES_NO_OPTION);

                if (resposta == JOptionPane.YES_OPTION) {

                    vendaAtual.removerItem(linhaSelecionada);
                    DefaultTableModel modelo = (DefaultTableModel) tblItens.getModel();
                    modelo.removeRow(linhaSelecionada);
                    lblTotal.setText(String.format("R$ %.2f", vendaAtual.getValorTotal()));

                }
            }
        }


    }//GEN-LAST:event_tblItensKeyReleased

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        TelaHistoricoVendas historicoVendas = new TelaHistoricoVendas();
        historicoVendas.setVisible(true);
        historicoVendas.setLocationRelativeTo(this);

    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
//        TelaCadastroCliente cadCliente = new TelaCadastroCliente();
//        cadCliente.setVisible(true);
//        cadCliente.setLocationRelativeTo(this);
        TelaListaClientes.abrir(this);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        TelaListaFuncionarios.abrir(this);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        TelaEstoque ListaEstoque = new TelaEstoque();
        ListaEstoque.setVisible(true);
        ListaEstoque.setLocationRelativeTo(this);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void txtCpfClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfClienteActionPerformed

        // Não precisa verificar se apertou Enter, esse evento já é o Enter.
        String cpf = txtCpfCliente.getText();

        // Limpa a máscara
        String cpfLimpo = cpf.replace(".", "").replace("-", "").replace(" ", "");

        if (!cpfLimpo.isEmpty()) {
            ClienteDAO dao = new ClienteDAO();
            Cliente clienteEncontrado = dao.consultar(cpf);

            if (clienteEncontrado != null) {
                lblNomeCliente.setText(clienteEncontrado.getNome());
                lblNomeCliente.setForeground(Color.BLUE);

                // Salva numa variável global que será usada para fechar a venda
                this.clienteDaVenda = clienteEncontrado;

                txtCodigo.requestFocus();

            } else {
                int resposta = JOptionPane.showConfirmDialog(this,
                        "Cliente não cadastrado! Deseja cadastrar agora?",
                        "Atenção",
                        JOptionPane.YES_NO_OPTION);

                if (resposta == JOptionPane.YES_OPTION) {
                    TelaCadastroCliente cadastroCli = new TelaCadastroCliente();
                    cadastroCli.setLocationRelativeTo(this);
                    cadastroCli.setVisible(true);
                    txtCodigo.requestFocus();
                } else {
                    //Contunua a venda como anônimo
                    lblNomeCliente.setText("Consumidor Final");
                    lblNomeCliente.setForeground(Color.BLACK); // Volta a cor normal
                    this.clienteDaVenda = null;
                    txtCodigo.requestFocus();
                }
            }
        } else {
            // Se der enter com o CPF vazio, assume que é anônimo e vai pro produto
            txtCodigo.requestFocus();
        }

    }//GEN-LAST:event_txtCpfClienteActionPerformed

    private void btnLoginSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginSistemaActionPerformed
        if (btnLoginSistema.getText().equals("Trocar Operador")) {
            controlarCaixa(false, null);

            TelaLogin login = new TelaLogin(this);
            login.setLocationRelativeTo(this);
            login.setVisible(true);
            txtCodigo.requestFocus();
        } else {
            TelaLogin login = new TelaLogin(this);
            login.setLocationRelativeTo(this);
            login.setVisible(true);
        }

    }//GEN-LAST:event_btnLoginSistemaActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        int resposta = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja sair?", "Confirmação", JOptionPane.YES_NO_OPTION);
        if (resposta == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnSairActionPerformed

    private void configurarDesign() {

        // Fonte padrão
        Font fontePadrao = new Font("Segoe UI", Font.PLAIN, 14);
        Font fonteDestaque = new Font("Segoe UI", Font.BOLD, 28);

        // Campos
        txtCodigo.setFont(fontePadrao);
        txtDescricao.setFont(fontePadrao);
        txtValor.setFont(fontePadrao);
        txtQuantidade.setFont(fontePadrao);

        // Labels
        jLabel1.setFont(fontePadrao);
        jLabel2.setFont(fontePadrao);
        jLabel3.setFont(fontePadrao);
        jLabel4.setFont(fontePadrao);
        jLabel5.setFont(new Font("Segoe UI", Font.BOLD, 18));

        // Total
        lblTotal.setFont(fonteDestaque);

        // Tabela
        tblItens.setFont(fontePadrao);
        tblItens.setRowHeight(30);

        // Botão sair
        btnSair.setFont(new Font("Segoe UI", Font.BOLD, 14));
        btnSair.putClientProperty("JButton.buttonType", "danger");
        btnSair.setFocusPainted(false);

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoginSistema;
    private javax.swing.JButton btnSair;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenu jMenuLogout;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEstoque;
    private javax.swing.JLabel lblNomeCliente;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblItens;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JFormattedTextField txtCpfCliente;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
