/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sistema.mercadinho.view;

import com.sistema.mercadinho.dao.HistoricoVendaDAO;
import com.sistema.mercadinho.dao.ProdutoDAO;
import com.sistema.mercadinho.model.ItemVenda;
import com.sistema.mercadinho.model.Produto;
import com.sistema.mercadinho.model.Venda;
import com.sistema.mercadinho.pagamento.Credito;
import com.sistema.mercadinho.pagamento.Debito;
import com.sistema.mercadinho.pagamento.Dinheiro;
import com.sistema.mercadinho.pagamento.MeioDePagamento;
import com.sistema.mercadinho.pagamento.Pix;
import com.sistema.mercadinho.view.util.GeradorCupom;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author rag
 */
public class TelaPagamento extends javax.swing.JDialog {

    /**
     * Creates new form TelaPagamento
     */
    private ProdutoDAO estoque;
    private Produto produtoSelelcionado;
    private Venda venda;
    private double pagar;
    private boolean pgtConfirmado = false;

    public TelaPagamento(java.awt.Frame parent, boolean modal, Venda venda) {
        super(parent, modal);
        initComponents();
        this.venda = venda;
        this.pagar = venda.getValorTotal();

        lblValorPagar.setText(String.format("R$ %.2f", venda.getValorTotal()));
        lstPagamento.requestFocus();
    }

    public boolean getPgtConfirmado() {
        return pgtConfirmado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblValorPagar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstPagamento = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pagamento");

        lblValorPagar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblValorPagar.setForeground(new java.awt.Color(0, 0, 153));
        lblValorPagar.setText("R$ 0,00");

        lstPagamento.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lstPagamento.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Dinheiro", "Pix", "Cartão de Débito", "Cartão de Crédito" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstPagamento.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstPagamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lstPagamentoKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(lstPagamento);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 0));
        jLabel1.setText("Pagar com:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(lblValorPagar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(124, 124, 124))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblValorPagar)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstPagamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lstPagamentoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            if (lstPagamento.getSelectedValue() == null) {
                JOptionPane.showMessageDialog(this, "Selecione a forma de pagamento!");
                return;
            }

            String escolhido = lstPagamento.getSelectedValue();
            MeioDePagamento meioSelecionado = null;

            try {
                switch (escolhido) {
                    case "Dinheiro":
                        String input = JOptionPane.showInputDialog(this, "\nQuanto o cliente entregou?");

                        if (input == null || input.trim().isEmpty()) {
                            return;
                        }

                        double valorRecebido = Double.parseDouble(input.replace(",", "."));
                        Dinheiro dinheiro = new Dinheiro();
                        dinheiro.setValorEntregue(valorRecebido);
                        meioSelecionado = dinheiro;
                        break;

                    case "Pix":
                        java.net.URL caminhoImagem = getClass().getResource("/com/sistema/mercadinho/imagens/qrcode.png");
                        javax.swing.ImageIcon iconPix = null;

                        if (caminhoImagem != null) {
                            // 1. Carrega a imagem original
                            iconPix = new javax.swing.ImageIcon(caminhoImagem);

                            // 2. REDIMENSIONA A IMAGEM (A Mágica acontece aqui)
                            java.awt.Image img = iconPix.getImage();
                            java.awt.Image newImg = img.getScaledInstance(200, 200, java.awt.Image.SCALE_SMOOTH); // 200x200 pixels
                            iconPix = new javax.swing.ImageIcon(newImg); // Cria o ícone novo pequeno
                        }

                        // 3. Mostra a janela (agora pequena)
                        int confirmacao = JOptionPane.showConfirmDialog(this,
                                "Valor Total: R$ " + String.format("%.2f", venda.getValorTotal()) + "\n\n"
                                + "Solicite ao cliente que escaneie o QR Code.\n"
                                + "O pagamento foi confirmado pelo banco?",
                                "Pagamento PIX",
                                JOptionPane.YES_NO_OPTION,
                                JOptionPane.PLAIN_MESSAGE,
                                iconPix);

                        if (confirmacao == JOptionPane.YES_OPTION) {
                            meioSelecionado = new Pix();
                        } else {
                            return; // Cancelou
                        }
                        break;
                    case "Cartão de Débito":
                        meioSelecionado = new Debito();
                        break;
                    case "Cartão de Crédito":
                        meioSelecionado = new Credito();
                        break;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Valor inválido!");
                return;
            }

            // Processa a venda
            venda.setFormaPagamento(meioSelecionado);
            ProdutoDAO daoProduto = new ProdutoDAO();

            boolean sucesso = venda.finalizarVenda(daoProduto);

            if (sucesso) {
                pgtConfirmado = true;

                HistoricoVendaDAO historico = new HistoricoVendaDAO();
                historico.adicionar(venda);

                for (ItemVenda item : venda.getItemVendaProdutos()) {
                    daoProduto.atualizar(item.getProduto());
                }
                
                // Chama o Gerador de Cupom
                GeradorCupom.emitir(venda);

                JOptionPane.showMessageDialog(this, "Venda finalizada com sucesso!");
                dispose();

            } else {
                if (escolhido.equals("Dinheiro")) {
                    JOptionPane.showMessageDialog(this, "Dinheiro insuficiente!");
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao finalizar venda.");
                }
            }
        }

    }//GEN-LAST:event_lstPagamentoKeyPressed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblValorPagar;
    private javax.swing.JList<String> lstPagamento;
    // End of variables declaration//GEN-END:variables
}
