/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sistema.mercadinho.view;

import com.sistema.mercadinho.dao.HistoricoVendaDAO;
import com.sistema.mercadinho.model.ItemVenda;
import com.sistema.mercadinho.model.Venda;
import com.sistema.mercadinho.view.util.DataRenderer;
import com.sistema.mercadinho.view.util.GeradorCupom;
import com.sistema.mercadinho.view.util.MoedaRenderer;
import com.sun.javafx.binding.StringFormatter;
import java.awt.event.KeyEvent;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JEditorPane;

/**
 *
 * @author rag
 */
public class TelaHistoricoVendas extends javax.swing.JFrame {

    /**
     * Creates new form TelaHistoricoVendas
     */
    private Venda venda;
    private HistoricoVendaDAO item;
    private ArrayList<Venda> listaDeVendas;

    public TelaHistoricoVendas() {
        initComponents();
        preencherTabela();
        tblHistorico.getColumnModel().getColumn(1).setCellRenderer(new DataRenderer());
        tblHistorico.getColumnModel().getColumn(2).setCellRenderer(new MoedaRenderer());
    }

    // carrega tudo ao abrir a tabela
    private void preencherTabela() {
        HistoricoVendaDAO dao = new HistoricoVendaDAO();
        this.listaDeVendas = dao.listar();
        preencherTabela(this.listaDeVendas);
    }

    private void preencherTabela(List<Venda> listaParaExibir) {
        
        this.listaDeVendas = (ArrayList<Venda>) listaParaExibir;
        
        DefaultTableModel modelo = (DefaultTableModel) tblHistorico.getModel();
        modelo.setRowCount(0);
        
        DateTimeFormatter formatador = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");

        for (Venda venda : listaParaExibir) {
            modelo.addRow(new Object[]{
                venda.getId(),
                venda.getHoraDaVenda().format(formatador),
                String.format("R$%.2f", venda.getValorTotal()),
                venda.getFormaPagamento().toString()
            });

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblHistorico = new javax.swing.JTable();
        lblHistoricoVendas = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JButton();
        txtFiltroData = new javax.swing.JFormattedTextField();
        btnFiltrar = new javax.swing.JButton();
        btnLimparFiltro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblHistorico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID da Venda:", "Data/Hora", "Valor Total:", "Pago com:"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHistorico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHistoricoMouseClicked(evt);
            }
        });
        tblHistorico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblHistoricoKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblHistorico);

        lblHistoricoVendas.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblHistoricoVendas.setText("Histórico de Vendas");

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        txtFiltroData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        txtFiltroData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFiltroDataActionPerformed(evt);
            }
        });

        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        btnLimparFiltro.setText("Limpar");
        btnLimparFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparFiltroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(lblHistoricoVendas))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnExcluir)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtFiltroData, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnFiltrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLimparFiltro)))))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblHistoricoVendas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFiltroData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFiltrar)
                    .addComponent(btnLimparFiltro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExcluir)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Método unificado para abrir o cupom
    public void abrirCupomSelecionado() {
        int linha = tblHistorico.getSelectedRow();

        if (linha != -1) {
            // PERIGO RESOLVIDO: Pegamos o objeto da lista usando a linha da tabela
            // (Assumindo que sua listaDeVendas está na mesma ordem da tabela)
            Venda vendaSelecionada = listaDeVendas.get(linha);

            // Usa a classe nova que criamos!
            GeradorCupom.emitir(vendaSelecionada);
        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma venda na tabela.");
        }
    }

    private void tblHistoricoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHistoricoMouseClicked
        if (evt.getClickCount() == 2) {
            abrirCupomSelecionado();
        }
    }//GEN-LAST:event_tblHistoricoMouseClicked

    private void tblHistoricoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblHistoricoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            evt.consume();
            abrirCupomSelecionado();
        }
    }//GEN-LAST:event_tblHistoricoKeyPressed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int linhaSelecionada = tblHistorico.getSelectedRow();
        DefaultTableModel modelo = (DefaultTableModel) tblHistorico.getModel();
        if (linhaSelecionada != -1) {
            int idVenda = (int) modelo.getValueAt(linhaSelecionada, 0);
            int resposta = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir a venda #" + idVenda + "?", "Confirmação", JOptionPane.YES_NO_OPTION);
            if (resposta == JOptionPane.YES_OPTION) {
                // Remove do HashMap
                item = new HistoricoVendaDAO();
                item.remover(idVenda);

                // Remove da tabela visual
                modelo.removeRow(linhaSelecionada);

                // Remove da lista em memória                
                this.listaDeVendas.remove(linhaSelecionada);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma venda para exluir.");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        try {
            String dataTexto = txtFiltroData.getText();

            DateTimeFormatter formatador = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            LocalDate dataFiltrada = LocalDate.parse(dataTexto, formatador);

            HistoricoVendaDAO dao = new HistoricoVendaDAO();
            List<Venda> listaFiltrada = dao.filtrarPorData(dataFiltrada);
            
            preencherTabela(listaFiltrada);
            
            // Total vendido no dia
            double totalDia = listaFiltrada.stream().mapToDouble(Venda::getValorTotal).sum();
            JOptionPane.showMessageDialog(this, "Foram encontradas: " + listaFiltrada.size() + " vendas.\nTotal do dia: R$ " + String.format("%.2f", totalDia));
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Data inválida ou erro ao filtrar! Use dia/mês/ano");
        }
    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void txtFiltroDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFiltroDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFiltroDataActionPerformed

    private void btnLimparFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparFiltroActionPerformed
        txtFiltroData.setText("");
        preencherTabela();
    }//GEN-LAST:event_btnLimparFiltroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnLimparFiltro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHistoricoVendas;
    private javax.swing.JTable tblHistorico;
    private javax.swing.JFormattedTextField txtFiltroData;
    // End of variables declaration//GEN-END:variables
}
